file-version: 1
# Additional environment variables for backend Servers (use "none" for none)
env-vars: PAPER_VELOCITY_SECRET=1234,FOO2=bar1
# Should the templates be pulled at start? (will take its time)
pull-start: true
# Docherhub Template for the Default-Servers.
lobby-template: anton691/simple-lobby:latest
# Player limit for default server.
lobby-max: 5
# Threshold for creating a new lobby server.
# When a server reaches this player count, a new server will be prepared.
# The current server will continue accepting players until it reaches the player limit (5),
# at which point new players will start connecting to the newly created lobby server.
lobby-min: 3
# If you enable this the server where the proxy itself is run will be used as a node ,so you don't need other nodes.
# This works without an ssh server too, but will still need docker but not ruby to be installed.
local-node: false
# Nodes, at least one.
nodes:
  example:
    ip: localhost
    username: notrootpls
    password: 1234 # type 'none', if you are not using a password
    privateKeyFile: /path/to/private.key  # type 'none', if you are not using a key
    port: 22  # default port 22
# Gamemodes which players can join.
gamemodes:
  Duels:
    templateName: anton691/simple-duels:latest
    neededPlayers: 2
    preload: 1
    env-vars: FOO=bar,FOO2=bar2 # Additional environment variables for this gamemode only (use "none" for none)
  Parkour:
    templateName: anton691/simple-parkour:latest
    neededPlayers: 1
    preload: 1
    env-vars: FOO=bar,FOO2=bar2 # Additional environment variables for this gamemode only (use "none" for none)