file-version: 1
# Use multi proxy mode
enabled: true
# Your HMAC secret, pls chnage it
hmac-secret: 1234
# Port for the multi proxy api server
port: 5000
# Define the other proxies
proxies:
  example:
    ip: 0.0.0.0 # IP of the other proxy
    port: 5000  # Port from the other api